import { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";

import { QueryProvider } from '@/components/QueryProvider'
import Navbar from '@/components/Navbar'
import NavDrawer from '@/components/NavDrawer'
import Toaster from '@/components/Toast'

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ 
  children 
}: { 
  children: ReactNode 
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <main className="pt-20">
            <Navbar />
            <section className="flex justify-between items-start">
              <NavDrawer />
              <div className="container p-5">
                {children}
              </div>
            </section>
            <Toaster />
          </main>
        </QueryProvider>
      </body>
    </html>
  );
}

